package com.ty.prop.scan.domain;

public class A {

    /**
     * This field was generated by MyBatis Generator. This field corresponds to the database column a.a_id
     * @mbg.generated  Fri Jan 06 01:07:19 CST 2017
     */
    private String aId;

    /**
     * This method was generated by MyBatis Generator. This method returns the value of the database column a.a_id
     * @return  the value of a.a_id
     * @mbg.generated  Fri Jan 06 01:07:19 CST 2017
     */
    public String getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator. This method sets the value of the database column a.a_id
     * @param aId  the value for a.a_id
     * @mbg.generated  Fri Jan 06 01:07:19 CST 2017
     */
    public void setaId(String aId) {
        this.aId = aId == null ? null : aId.trim();
    }
}